package Forms;

import Compound.AddressInfo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.*;
import java.util.List;

/**
 * Created by Sanket on 05-02-2017.
 */
public class Address {
    private JLabel addressType;
    protected JComboBox addressTypecomboBox;
    private JLabel address;
    protected JTextField addressTextField;
    private JLabel city;
    private JLabel state;
    private JLabel country;
    private JLabel pincode;
    protected JTextField cityTextField;
    protected JTextField stateTextField;
    protected JTextField countryTextField;
    protected JTextField pincodeTextField;
    protected JPanel addressPanel;
    private JButton cancelButton;
    private JButton addButton;

    public Address() {
        cancelButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                CreateForm form = new CreateForm();
                form.getBasicForm().addAddress.setEnabled(true);
                form.getBasicForm().addressframe.dispose();
            }
        });
        addButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                CreateForm form = new CreateForm();
                if (cityTextField.getText().isEmpty() || stateTextField.getText().isEmpty() || countryTextField.getText().isEmpty() || pincodeTextField.getText().isEmpty() || addressTextField.getText().isEmpty())
                    JOptionPane.showMessageDialog(form.getBasicForm().addressframe, "Empty Fields");

                List<AddressInfo> addressInfoList = form.getInfo().getAddressInfo();
                AddressInfo addressInfo = new AddressInfo();
                addressInfo.setAddress(addressTextField.getText());
                addressInfo.setCity(cityTextField.getText());
                addressInfo.setState(stateTextField.getText());
                addressInfo.setCountry(countryTextField.getText());
                addressInfo.setZipCode(pincodeTextField.getText());
                addressInfo.setAddressType(addressTypecomboBox.getSelectedItem().toString());
                addressInfoList.add(addressInfo);
                form.getInfo().setAddressInfo(addressInfoList);

                form.getBasicForm().addressframe.dispose();
                form.getBasicForm().addAddress.setEnabled(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addressPanel = new JPanel();
        addressPanel.setLayout(new GridBagLayout());
        addressType = new JLabel();
        addressType.setText("Address Type");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        addressPanel.add(addressType, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(spacer1, gbc);
        addressTypecomboBox = new JComboBox();
        addressTypecomboBox.setMaximumRowCount(3);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Mailing");
        defaultComboBoxModel1.addElement("Physical");
        defaultComboBoxModel1.addElement("Mailing & Physical");
        addressTypecomboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(addressTypecomboBox, gbc);
        address = new JLabel();
        address.setText("Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        addressPanel.add(address, gbc);
        city = new JLabel();
        city.setText("City");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        addressPanel.add(city, gbc);
        state = new JLabel();
        state.setText("State");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        addressPanel.add(state, gbc);
        country = new JLabel();
        country.setText("Country");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        addressPanel.add(country, gbc);
        pincode = new JLabel();
        pincode.setFocusable(true);
        pincode.setText("Pincode");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        addressPanel.add(pincode, gbc);
        cityTextField = new JTextField();
        cityTextField.setEnabled(true);
        cityTextField.setText("Enter City");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(cityTextField, gbc);
        stateTextField = new JTextField();
        stateTextField.setText("Enter State");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(stateTextField, gbc);
        countryTextField = new JTextField();
        countryTextField.setText("Enter Country");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(countryTextField, gbc);
        pincodeTextField = new JTextField();
        pincodeTextField.setEditable(true);
        pincodeTextField.setText("Enter Pincode");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(pincodeTextField, gbc);
        addressTextField = new JTextField();
        addressTextField.setText("Enter Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addressPanel.add(addressTextField, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        addressPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        addressPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        addressPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        addressPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        addressPanel.add(spacer6, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        addressPanel.add(cancelButton, gbc);
        addButton = new JButton();
        addButton.setText("Add");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.EAST;
        addressPanel.add(addButton, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        addressPanel.add(spacer7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addressPanel;
    }
}
