package Forms;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Created by Sanket on 05-02-2017.
 */
public class BasicForm {
    protected JTextField nameTextField;
    private JLabel name;
    private JLabel org;
    protected JTextField organisationNameTextField;
    protected JTextField positionTextField;
    private JLabel position;
    protected JTextField telephoneNoTextField;
    protected JTextField tDDTelephoneNoTextField;
    protected JTextField fascimileTelephoneNoTextField;
    private JLabel telephone;
    private JLabel telephoneTDD;
    private JLabel telephoneFascimile;
    protected JFrame addressframe;

    public BasicForm() {
        addAddress.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                addAddress.setEnabled(false);
                addressframe = new JFrame("Address");
                addressframe.setContentPane(new Address().addressPanel);
                addressframe.setDefaultCloseOperation(addressframe.DO_NOTHING_ON_CLOSE);
                addressframe.setResizable(false);
                addressframe.setSize(400, 400);
                addressframe.setVisible(true);
        }
        });
        cancelButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                CreateForm form = new CreateForm();
                form.getEmptyFrame().dispose();
                form.getInitialFrame().setVisible(true);

            }
        });
        saveButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                CreateForm form = new CreateForm();
                form.submitForm();
            }
        });
    }


    private JLabel address;
    protected JButton addAddress;
    private JButton addTelephone1;
    private JButton addTelephone2;
    private JButton addTelephone3;
    protected JTextField hoursTextField;
    private JLabel hours;
    protected JTextField instructionTextField;
    private JLabel instruction;
    private JButton cancelButton;
    private JButton saveButton;
    protected JPanel form;
    private JLabel primaryInfo;
    private JLabel addressInfo;
    private JLabel contactInfo;
    private JLabel serviceInfo;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        form = new JPanel();
        form.setLayout(new GridBagLayout());
        form.setMaximumSize(new Dimension(600, 600));
        form.setMinimumSize(new Dimension(360, 600));
        form.setPreferredSize(new Dimension(600, 600));
        form.setRequestFocusEnabled(true);
        name = new JLabel();
        name.setText("Name");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(name, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(spacer1, gbc);
        nameTextField = new JTextField();
        nameTextField.setText("Enter Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(nameTextField, gbc);
        org = new JLabel();
        org.setText("Organisation Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(org, gbc);
        organisationNameTextField = new JTextField();
        organisationNameTextField.setText("Enter Organisation Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(organisationNameTextField, gbc);
        position = new JLabel();
        position.setText("Position");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(position, gbc);
        positionTextField = new JTextField();
        positionTextField.setText("Enter Position");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(positionTextField, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer3, gbc);
        address = new JLabel();
        address.setText("Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(address, gbc);
        telephone = new JLabel();
        telephone.setText("Telephone No.");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(telephone, gbc);
        telephoneNoTextField = new JTextField();
        telephoneNoTextField.setText("Enter Telephone No.");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(telephoneNoTextField, gbc);
        telephoneTDD = new JLabel();
        telephoneTDD.setText("Telephone TDD");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 19;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(telephoneTDD, gbc);
        tDDTelephoneNoTextField = new JTextField();
        tDDTelephoneNoTextField.setText("Enter TDD Telephone No.");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 19;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(tDDTelephoneNoTextField, gbc);
        telephoneFascimile = new JLabel();
        telephoneFascimile.setText("Telephone Fascimile");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 21;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(telephoneFascimile, gbc);
        fascimileTelephoneNoTextField = new JTextField();
        fascimileTelephoneNoTextField.setText("Enter Fascimile Telephone No");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 21;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(fascimileTelephoneNoTextField, gbc);
        addAddress = new JButton();
        addAddress.setText("Add New Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        form.add(addAddress, gbc);
        addTelephone1 = new JButton();
        addTelephone1.setText("Add New");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 17;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(addTelephone1, gbc);
        addTelephone2 = new JButton();
        addTelephone2.setText("Add New");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 19;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(addTelephone2, gbc);
        addTelephone3 = new JButton();
        addTelephone3.setText("Add New");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 21;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(addTelephone3, gbc);
        hours = new JLabel();
        hours.setText("Hours of Service");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 26;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(hours, gbc);
        hoursTextField = new JTextField();
        hoursTextField.setText("Enter Hours");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 26;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(hoursTextField, gbc);
        instruction = new JLabel();
        instruction.setText("Instruction");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 28;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(instruction, gbc);
        instructionTextField = new JTextField();
        instructionTextField.setEditable(true);
        instructionTextField.setEnabled(true);
        instructionTextField.setName("");
        instructionTextField.setText("Enter Instruction");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 28;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(instructionTextField, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 27;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 22;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 20;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 17;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        form.add(spacer10, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 30;
        form.add(cancelButton, gbc);
        saveButton = new JButton();
        saveButton.setHideActionText(false);
        saveButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 30;
        gbc.anchor = GridBagConstraints.EAST;
        form.add(saveButton, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 29;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer11, gbc);
        final JSeparator separator1 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        form.add(separator1, gbc);
        primaryInfo = new JLabel();
        primaryInfo.setText("Primary Information");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(primaryInfo, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer12, gbc);
        addressInfo = new JLabel();
        addressInfo.setText("Address Information");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(addressInfo, gbc);
        final JSeparator separator2 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.BOTH;
        form.add(separator2, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer13, gbc);
        contactInfo = new JLabel();
        contactInfo.setText("Contact Information");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 14;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(contactInfo, gbc);
        final JSeparator separator3 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.BOTH;
        form.add(separator3, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer14, gbc);
        serviceInfo = new JLabel();
        serviceInfo.setText("Service Information");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 23;
        gbc.anchor = GridBagConstraints.WEST;
        form.add(serviceInfo, gbc);
        final JSeparator separator4 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 24;
        gbc.fill = GridBagConstraints.BOTH;
        form.add(separator4, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 25;
        gbc.fill = GridBagConstraints.VERTICAL;
        form.add(spacer15, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return form;
    }
}

